version: '3.8'

services:
  mariadb:
    image: mariadb:11.7
    container_name: rag-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: ragdb
      MARIADB_USER: raguser
      MARIADB_PASSWORD: ragpass
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d

  app:
    build: ./app
    env_file:
      - .env
    container_name: wiki_checker
    depends_on:
      - mariadb
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["python", "main.py"]
